### ISSUE TITLE
migrate to jupyterlab

### ISSUE THREAD

**Issue by leagoz** [jberryman566/UVIC-Drug-Checking#6]
We are currently using the 'ol jupyterhub, but Belaid keeps recommending fancier features available in jupyterlab. Jorin suspects that this could be an upgrade, rather than a 'replacement'. We could consider making the switch sometime.

**Comment by jberryman566** [comment]
Jupyterlab seems to be running fine with the url extension changed from "/tree" to "/lab". Closing issue.
